#
# SPDX-License-Identifier: Apache-2.0
#

trigger:
  - master
  - release-1.4

variables:
  NODE_VER: '12.x'

jobs:
  - job: CardioGene_go
    displayName: FabCar (Go)
    pool:
      vmImage: ubuntu-18.04
    dependsOn: []
    timeoutInMinutes: 60
    steps:
      - template: install-deps.yml
      - template: install-fabric.yml
      - template: CardioGene-go.yml

  - job: test_network
    displayName: Start the test network
    pool:
      vmImage: ubuntu-18.04
    dependsOn: []
    timeoutInMinutes: 60
    steps:
      - template: install-deps.yml
      - template: install-fabric.yml
      - template: testnetwork.yml

  - job: CardioGene_java
    displayName: FabCar (Java)
    pool:
      vmImage: ubuntu-18.04
    dependsOn: []
    timeoutInMinutes: 60
    steps:
      - template: install-deps.yml
      - template: install-fabric.yml
      - template: CardioGene-java.yml

  - job: CardioGene_javascript
    displayName: FabCar (JavaScript)
    pool:
      vmImage: ubuntu-18.04
    dependsOn: []
    timeoutInMinutes: 60
    steps:
      - template: install-deps.yml
      - template: install-fabric.yml
      - template: CardioGene-javascript.yml

  - job: CardioGene_typescript
    displayName: FabCar (TypeScript)
    pool:
      vmImage: ubuntu-18.04
    dependsOn: []
    timeoutInMinutes: 60
    steps:
      - template: install-deps.yml
      - template: install-fabric.yml
      - template: CardioGene-typescript.yml

  - job: commercialpaper_javascript
    displayName: CommercialPaper (JavaScript)
    pool:
      vmImage: ubuntu-18.04
    dependsOn: []
    timeoutInMinutes: 60
    steps:
      - template: install-deps.yml
      - template: install-fabric.yml
      - template: commercialpaper-javascript.yml

  - job: commercialpaper_java
    displayName: CommercialPaper (Java)
    pool:
      vmImage: ubuntu-18.04
    dependsOn: []
    timeoutInMinutes: 60
    steps:
      - template: install-deps.yml
      - template: install-fabric.yml
      - template: commercialpaper-java.yml

  - job: commercialpaper_go
    displayName: CommercialPaper (Go)
    pool:
      vmImage: ubuntu-18.04
    dependsOn: []
    timeoutInMinutes: 60
    steps:
      - template: install-deps.yml
      - template: install-fabric.yml
      - template: commercialpaper-go.yml
